### ISSUE TITLE
패션 사이트 정보 크롤링

### ISSUE THREAD

**Issue by minji-dev** [minji-dev/OSS_team12#3]
## 목적
> 정보를 받아와서 옷을 추천해준다.

## 작업 상세 내용
- [ ] 패션 사이트(무신사, 에이블리) 정보 크롤링

**Comment by peter0107** [comment]
무신사 크롤링코드(http.js)가져오는중에 에러발생
`const https=require("https");
const parser=require("node-html-parser");`


**Uncaught ReferenceError: require is not defined**

**Comment by minji-dev** [comment]
> 무신사 크롤링코드(http.js)가져오는중에 에러발생 `const https=require("https"); const parser=require("node-html-parser");`
> 
> **Uncaught ReferenceError: require is not defined**

npm install require 해보세용

**Comment by peter0107** [comment]
> > 무신사 크롤링코드(http.js)가져오는중에 에러발생 `const https=require("https"); const parser=require("node-html-parser");`
> > **Uncaught ReferenceError: require is not defined**
> 
> npm install require 해보세용

이거해도 안되네요..ㅜㅜ
현재 snd.html에서 `<script src="../http.js"></script>`로 js파일을 참조해서
`const https=require("https");
const parser=require("node-html-parser");




function Get_Info(){
    


    console.log("getting info");
    const header={
        headers:{
          "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
        }
      }
    let url="https://www.musinsa.com/search/musinsa/integration?type=&q="+"패딩";
    https.get(url,header,(res)=>{
        let data="";
        res.on("data",(d)=>{
            data+=d;
        })
        res.on("end",()=>{
            
            //브랜드
            let root=parser.parse(data);
            root.querySelectorAll(".item_title").forEach((list)=>{
                console.log(list.innerText.trim());
                document.getElementById('brand').value=list[0].innerText.trim();
            });
            console.log("");
            //제품이름
            root.querySelectorAll(".list_info a[title]").forEach((list)=>{
                console.log(list.innerText.trim());
                document.getElementById("name").value=list[0].innerText.trim();
            });
            console.log("");
            //가격
            root.querySelectorAll(".price").forEach((list)=>{
                console.log(list.innerText.trim());
                document.getElementById("price").value=list[0].innerText.trim();
            });
            console.log("");
            //사진 url
            root.querySelectorAll("div.list_img > a > img.lazyload.lazy").forEach((list)=>{
                console.log(list.attributes['data-original']);
            });
    
        });
    })
}


document.getElementById('test').onclick=Get_Info;

`
가져올려하는데 잘안되네요..

**Comment by minji-dev** [comment]
document.getElementById('test').onclick=Get_Info;

이 코드는 프론트 ejs 파일 중 <script> 쪽에서 쓸 수 있는 코드야! api 요청으로 정보 주고 받아야 하는데
https://itsjh.tistory.com/7
이런 블로그 한 번 참고해부세요
